// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	flowstatMapProtoCount   = "proto_count"
	flowstatProgXdpFlowstat = "xdp_flowstat"
)

// loadFlowstat returns the embedded CollectionSpec for flowstat.
func loadFlowstat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowstatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flowstat: %w", err)
	}

	return spec, err
}

// loadFlowstatObjects loads flowstat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowstatObjects
//	*flowstatPrograms
//	*flowstatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowstatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlowstat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowstatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowstatSpecs struct {
	flowstatProgramSpecs
	flowstatMapSpecs
	flowstatVariableSpecs
}

// flowstatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowstatProgramSpecs struct {
	XdpFlowstat *ebpf.ProgramSpec `ebpf:"xdp_flowstat"`
}

// flowstatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowstatMapSpecs struct {
	ProtoCount *ebpf.MapSpec `ebpf:"proto_count"`
}

// flowstatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowstatVariableSpecs struct {
}

// flowstatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowstatObjects struct {
	flowstatPrograms
	flowstatMaps
	flowstatVariables
}

func (o *flowstatObjects) Close() error {
	return _FlowstatClose(
		&o.flowstatPrograms,
		&o.flowstatMaps,
	)
}

// flowstatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowstatMaps struct {
	ProtoCount *ebpf.Map `ebpf:"proto_count"`
}

func (m *flowstatMaps) Close() error {
	return _FlowstatClose(
		m.ProtoCount,
	)
}

// flowstatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowstatVariables struct {
}

// flowstatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowstatPrograms struct {
	XdpFlowstat *ebpf.Program `ebpf:"xdp_flowstat"`
}

func (p *flowstatPrograms) Close() error {
	return _FlowstatClose(
		p.XdpFlowstat,
	)
}

func _FlowstatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowstat_bpfel.o
var _FlowstatBytes []byte
